version: "3.8"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=rarefydb
      - MYSQL_ROOT_PASSWORD=AVNS_z0jjtOLvAdpvIFAPkfu
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  db:
    driver: local
